import React, { FC } from 'react'
import Head from 'next/head'
import Footer from '../Footer'
import Header from '../Header'
import styled from 'styled-components'
import Main from '../Main'
import Divider from '../UI/Divider'

interface Props {
	title: string
}

const PageWrapper: FC<Props> = props => {
	return (
		<Root>
			<Head>
				<title>{props.title}</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<Header />
			<Main>{props.children}</Main>
			<Divider />
			<Footer />
		</Root>
	)
}

export default PageWrapper

const Root = styled.div`
	height: 100%;
	& > main {
		min-height: 100vh;
	}
`
